Algoritmo "ExerPortugues"
// Disciplina   : [Lógica de Programação e Javascript]
// Professor   : Jailson 
// Descrição   : Exercicio
// Autor(a)    : Vinicius
// Data atual  : 01/09/2021
Var
// Seção de Declarações das variáveis 
x, r, cont:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont<-1
repita
escreval("Digite o valor de X")
leia(x)
r<-x*3

escreval("O valor de R é: ", r)

cont<-cont+1
ate (cont>5)


Fimalgoritmo