Algoritmo "Exibir Mensagem"
// Disciplina   : [Lógica de Programação e Javascript]
// Professor   : Jailson
// Descrição   : Exibe uma mensagem
// Autor(a)    : Vinicius
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Vinicius Rodrigues")
escreval("Itaquaquaquecetuba")
escreval("24/08/2021")

Fimalgoritmo