Algoritmo "L03D"
// Disciplina   : [Lógica de Programação e Javascript]
// Professor   : Jailson 
// Descrição   : Exerciciolacoderepeticao
// Autor(a)    : Vinicius
// Data atual  : 02/09/2021
Var
// Seção de Declarações das variáveis 
n1:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
n1<-1
escreval(n1)
enquanto (n1<20) faca
n1<-n1+2
se n1 mod 2=1 e (n1<20) entao

escreval (n1)
fimse
fimenquanto
fimalgoritmo
