Algoritmo "L05J"
// Disciplina   : [Lógica de Programação e Javascript]
// Professor   : Jailson 
// Descrição   : Graus para fahreheit
// Autor(a)    : Vinicius
// Data atual  : 06/09/2021
Var
// Seção de Declarações das variáveis 
c:inteiro
f:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para c de 0 ate 100 passo 10 faca

f<-(9*c+160)/5

escreval (c, "°C é equivale à ", f, "° F")

fimpara

Fimalgoritmo