Algoritmo "lacoderepeticao"
// Disciplina   : [Lógica de Programação e Javascript]
// Professor   : Jailson 
// Descrição   : Laço de repetição
// Autor(a)    : Vinicius
// Data atual  : 01/09/2021
Var
// Seção de Declarações das variáveis 
contadora:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
enquanto contadora<10 faca
escreval("Vinicius")
contadora<-contadora+1
fimenquanto

Fimalgoritmo